[package]
name = "ttyrec"
version = "0.1.1"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

description = "reads and writes ttyrec files"
license = "MIT"
repository = "https://git.tozt.net/ttyrec"
readme = "README.md"
keywords = ["ttyrec"]
categories = ["parser-implementations"]

[dependencies]
futures = { version = "0.1.29", optional = true }
snafu = "0.5"
tokio = { version = "0.1.22", optional = true }

[features]
default = ["async"]
async = ["tokio", "futures"]
